Add retry

diff --git a/run b/run
--- a/run
+++ b/run
@@ -5,6 +5,26 @@ set -eo pipefail
 
 trap 'kill %1; kill %2' SIGINT
 
+function retry()
+{
+  local n=0
+  local try=$1
+  local cmd="${@: 2}"
+  [[ $# -le 1 ]] && {
+    echo "Usage $0 <retry_number> <Command>";
+  }
+
+  until [[ $n -ge $try ]]
+  do
+    $cmd && break || {
+      echo "Command Fail.."
+      ((n++))
+      echo "retry $n ::"
+      sleep 1;
+    }
+  done
+}
+
 GIT_BASE_DIR=$(git rev-parse --show-toplevel)
 VERSION=$(cat ${GIT_BASE_DIR}/target/classes/version.txt)
 
@@ -43,25 +63,24 @@ BASE_ARGS=(
   org.elkoserver.server.context.ContextServerBoot
 )
 
-ls -lah
-ls -lah target
+find .
 
 if [ "${SHOULD_UPDATE_SCHEMA}" == true ]; then
   cd ${GIT_BASE_DIR}/db
-  make db
+  retry 60 "make db"
   cd ..
 fi
 
 # Starts the Habitat-to-Elko bridge process if requested.
 if [ "${SHOULD_RUN_BRIDGE}" == true ]; then
   if [ "${SHOULD_BACKGROUND_BRIDGE}" == true ]; then
-    supervisor -w bridge -- bridge/Habitat2ElkoBridge.js -l "${BRIDGE_HOST}:${BRIDGE_PORT}" &
+    supervisor -w bridge -- ${GIT_BASE_DIR}/bridge/Habitat2ElkoBridge.js -l "${BRIDGE_HOST}:${BRIDGE_PORT}" &
   else
-    supervisor -w bridge -- bridge/Habitat2ElkoBridge.js -l "${BRIDGE_HOST}:${BRIDGE_PORT}" 
+    supervisor -w bridge -- ${GIT_BASE_DIR}/bridge/Habitat2ElkoBridge.js -l "${BRIDGE_HOST}:${BRIDGE_PORT}" 
   fi
 fi
 
 # Starts the Habitat Elko server if requested.
 if [ "${SHOULD_RUN_NEOHABITAT}" == true ]; then
-  java -jar target/neohabitat-${VERSION}.jar "${BASE_ARGS[@]}" "${@}"
+  java -jar ${GIT_BASE_DIR}/target/neohabitat-${VERSION}.jar "${BASE_ARGS[@]}" "${@}"
 fi
